### ISSUE TITLE
Get it working for all zoom levels on https://projects.propublica.org/miseducation/

### ISSUE THREAD

**Issue by Chickensoupwithrice** [webrecorder/mapbox-driver#1]
Tessa's work so far gives us a working 'first glance' but interacting with the MapBox element, especially at higher zoom levels leads to lots of 404 requests. At this stage we'd like to be able to archive the mapbox element specifically for https://projects.propublica.org/miseducation/ 

This will involve hard coding api endpoints and map box edges and stuff like that, but that's okay for now.

**Comment by Shrinks99** [comment]
From call: Because of mapbox billing, building this is potentially going to be very uncool for some folks. 🙃
